M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date  4.02.2026 (ср)  9:47:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-04T09:47:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X11.61Y44.97
X17.39Y44.97
T2
X7.5Y49.0
X7.5Y2.0
X21.5Y49.0
X21.5Y2.0
M30
